baseurl = "mindymallory.github.io"
title = "Mindy L. Mallory"
copyright = "&copy; 2017 Mindy L. Mallory"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-70608433-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Mindy L. Mallory"
  role = "Associate Professor, Agricultural and Consumer Economics"
  organization = "University of Illinois"
  organization_url = "http://illinois.edu/"
  avatar = "mallory-headshot.jpg"
  email = "mallorym@illinois.edu"
  address = "319 Mumford Hall, 1301 W Gregory Dr., Urbana, IL 61801"
  office_hours = "Email for appointment"
  phone = "217-333-6547"
  skype =  ""
  telegram = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com)
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r"]
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:mallorym@illinois.edu"

  [[params.social]]
    icon = "university"
    icon_pack = "fa"
    link = "http://ace.illinois.edu/directory/mallorym"
    
  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/ace_prof"
    
  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/mindymallory/"  

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=bp9U6boAAAAJ&hl=en"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/mindymallory"

  

 
    

    
 
# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 3
  
[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 4


[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4
  
[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 5  

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6
  
[[menu.main]]
  name = "CV-HTML"
  url = "http://mindymallory.github.io/CV/"
  weight = 7  
  
[[menu.main]]
  name = "CV-PDF"
  url = "http://mindymallory.github.io/pdfs/CV-Mallory.pdf"
  weight = 8  

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"